-- 公网留言板初始化（Supabase SQL Editor 直接执行）

create table if not exists public.feedback_messages (
    id bigint generated by default as identity primary key,
    name text not null default '匿名玩家',
    message text not null check (char_length(message) between 1 and 600),
    created_at timestamptz not null default now()
);

alter table public.feedback_messages enable row level security;

drop policy if exists "feedback_public_read" on public.feedback_messages;
drop policy if exists "feedback_public_insert" on public.feedback_messages;

-- 允许匿名读取
create policy "feedback_public_read"
on public.feedback_messages
for select
to anon
using (true);

-- 允许匿名写入
create policy "feedback_public_insert"
on public.feedback_messages
for insert
to anon
with check (true);

grant select, insert on table public.feedback_messages to anon;
grant usage, select on sequence public.feedback_messages_id_seq to anon;
